#!/usr/bin/env bash
# Install global terminal shortcuts for opencode-multi-ai into ~/.local/bin
#
#   op-ai …                  primary (tabbed multi-provider)
#   op-xai …                 xAI-forced alias
#   op-codex …               Codex-forced alias
#   opencode-multi-ai …      package alias
#   opencode-multi-xai …     historical alias → same CLI
#   opencode-multi-codex …   historical alias → same CLI
#   xai-multi …              historical alias
#   codex-multi …            historical alias
#
# Env (first match wins):
#   MULTI_AI_BIN_DIR | MULTI_XAI_BIN_DIR | MULTI_CODEX_BIN_DIR
#   default: ~/.local/bin
#
# Usage:
#   bash scripts/install-cli.sh
#   bash scripts/install-cli.sh --path   # also ensure PATH in shell rc
#   npm run install-cli
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI="$ROOT/scripts/cli.ts"
BIN_DIR="${MULTI_AI_BIN_DIR:-${MULTI_XAI_BIN_DIR:-${MULTI_CODEX_BIN_DIR:-$HOME/.local/bin}}}"
FIX_PATH=0

for arg in "$@"; do
  case "$arg" in
    --path|--fix-path) FIX_PATH=1 ;;
    -h|--help)
      echo "Usage: bash scripts/install-cli.sh [--path]"
      echo "  --path  Append ~/.local/bin to ~/.zshrc and/or ~/.bashrc if missing"
      echo ""
      echo "Env:"
      echo "  MULTI_AI_BIN_DIR     Shim dir (fallback: MULTI_XAI_BIN_DIR / MULTI_CODEX_BIN_DIR)"
      exit 0
      ;;
  esac
done

resolve_runner() {
  if command -v bun >/dev/null 2>&1; then
    command -v bun
    return 0
  fi
  if [[ -x "$HOME/.bun/bin/bun" ]]; then
    echo "$HOME/.bun/bin/bun"
    return 0
  fi
  return 1
}

BUN_BIN="$(resolve_runner || true)"
if [[ -z "${BUN_BIN:-}" ]]; then
  echo "error: bun not found on PATH" >&2
  echo "Install bun: https://bun.sh  (required to run scripts/cli.ts)" >&2
  exit 1
fi

if [[ ! -f "$CLI" ]]; then
  echo "error: missing $CLI" >&2
  exit 1
fi

if [[ ! -d "$ROOT/node_modules" ]]; then
  echo "note: node_modules missing — run npm install / bun install in $ROOT first" >&2
fi

mkdir -p "$BIN_DIR"

write_shim() {
  local name="$1"
  local target="$BIN_DIR/$name"
  cat >"$target" <<EOF
#!/usr/bin/env bash
# opencode-multi-ai global CLI shim — generated by scripts/install-cli.sh
# Repo: $ROOT
set -euo pipefail
ROOT="$ROOT"
CLI="\$ROOT/scripts/cli.ts"
BUN="$BUN_BIN"
if [[ ! -f "\$CLI" ]]; then
  echo "error: CLI source missing: \$CLI" >&2
  echo "Re-run install from the opencode-multi-ai repo." >&2
  exit 1
fi
if [[ ! -x "\$BUN" ]] && ! command -v bun >/dev/null 2>&1; then
  echo "error: bun not found (was: \$BUN)" >&2
  exit 1
fi
if [[ ! -x "\$BUN" ]]; then
  BUN="\$(command -v bun)"
fi
# Always run with repo as cwd so relative imports / package resolve work
cd "\$ROOT"
exec "\$BUN" "\$CLI" "\$@"
EOF
  chmod +x "$target"
}

# All shims point at the merged multi-ai CLI (safe during dual-install transition).
write_shim "op-ai"
write_shim "op-xai"
write_shim "op-codex"
write_shim "opencode-multi-ai"
write_shim "opencode-multi-xai"
write_shim "opencode-multi-codex"
write_shim "xai-multi"
write_shim "codex-multi"

# Remove legacy one-shot wrappers (xai-list, xai-add, codex-list, …) if present
LEGACY_CMDS=(
  status list add limits quota health switch remove
  enable disable label tag note refresh flag unflag prune help priority
)
for cmd in "${LEGACY_CMDS[@]}"; do
  rm -f "$BIN_DIR/xai-$cmd" "$BIN_DIR/codex-$cmd"
done

ensure_path_rc() {
  local rc="$1"
  local line='export PATH="$HOME/.local/bin:$PATH"'
  [[ -f "$rc" ]] || touch "$rc"
  if grep -qF '.local/bin' "$rc" 2>/dev/null; then
    echo "  PATH already referenced in $rc"
    return 0
  fi
  {
    echo ""
    echo "# opencode-multi-ai / op-ai global CLI"
    echo "$line"
  } >>"$rc"
  echo "  appended PATH to $rc"
}

echo "Installed global CLI into $BIN_DIR"
echo "  op-ai"
echo "  op-xai"
echo "  op-codex"
echo "  opencode-multi-ai"
echo "  opencode-multi-xai / opencode-multi-codex / xai-multi / codex-multi (aliases)"
echo "  → $BUN_BIN $CLI"
echo ""

PATH_OK=0
if echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  PATH_OK=1
fi

if [[ "$FIX_PATH" -eq 1 ]]; then
  echo "Ensuring $BIN_DIR is on PATH in shell rc…"
  case "${SHELL:-}" in
    */zsh) ensure_path_rc "$HOME/.zshrc" ;;
    */bash) ensure_path_rc "$HOME/.bashrc" ;;
    *)
      [[ -f "$HOME/.zshrc" ]] && ensure_path_rc "$HOME/.zshrc"
      [[ -f "$HOME/.bashrc" ]] && ensure_path_rc "$HOME/.bashrc"
      if [[ ! -f "$HOME/.zshrc" && ! -f "$HOME/.bashrc" ]]; then
        ensure_path_rc "$HOME/.profile"
      fi
      ;;
  esac
  export PATH="$BIN_DIR:$PATH"
  PATH_OK=1
  echo ""
fi

echo "Try (global, any directory):"
echo "  op-ai tui"
echo "  op-ai help"
echo "  op-ai list"
echo "  op-xai list"
echo "  op-codex list"
echo "  op-ai status"
echo "  op-ai limits --probe"
echo "  op-ai add --provider xai"
echo ""

if [[ "$PATH_OK" -eq 0 ]]; then
  echo "NOTE: $BIN_DIR is not on PATH in this shell."
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo "Or permanently:"
  echo "  bash scripts/install-cli.sh --path"
  echo "  # then: source ~/.zshrc   (or open a new terminal)"
elif ! command -v op-ai >/dev/null 2>&1; then
  export PATH="$BIN_DIR:$PATH"
  hash -r 2>/dev/null || true
fi

if command -v op-ai >/dev/null 2>&1; then
  echo "Verified: $(command -v op-ai)"
  op-ai help 2>/dev/null | head -3 || true
fi
